/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.mycompany.gestionvotantes.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class BuscarPorRutVentana extends javax.swing.JDialog {

    //declaration variable
    private JFrame MenuPrincipal;
    private LugarVotacion valpo = new LugarVotacion();
    
    
    public BuscarPorRutVentana(java.awt.Frame parent, boolean modal, LugarVotacion valparaiso) {
        super(parent, modal);
        MenuPrincipal = (JFrame) parent;
        valpo = valparaiso;
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundBuscarPorRut = new javax.swing.JPanel();
        PanelTitulo = new javax.swing.JPanel();
        LBLTITULO = new javax.swing.JLabel();
        TextEntraRut = new javax.swing.JTextField();
        LBLIntroduzcaRut = new javax.swing.JLabel();
        LBLNombre = new javax.swing.JLabel();
        LBLRut = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JButton();
        BotonVolverMenuPrincipal = new javax.swing.JButton();
        TextSalidaDeNombre = new javax.swing.JTextField();
        TextSalidaDeMesa = new javax.swing.JTextField();
        LBLMesa = new javax.swing.JLabel();
        TextSalidaDeRut = new javax.swing.JTextField();
        LBLVocal = new javax.swing.JLabel();
        TextSalidaDeVocal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BackgroundBuscarPorRut.setBackground(new java.awt.Color(0, 153, 204));

        PanelTitulo.setBackground(new java.awt.Color(0, 153, 204));

        LBLTITULO.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LBLTITULO.setForeground(new java.awt.Color(0, 0, 0));
        LBLTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTITULO.setText("BUSCAR POR RUT");

        javax.swing.GroupLayout PanelTituloLayout = new javax.swing.GroupLayout(PanelTitulo);
        PanelTitulo.setLayout(PanelTituloLayout);
        PanelTituloLayout.setHorizontalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LBLTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PanelTituloLayout.setVerticalGroup(
            PanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTituloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LBLTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        TextEntraRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEntraRutActionPerformed(evt);
            }
        });

        LBLIntroduzcaRut.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LBLIntroduzcaRut.setForeground(new java.awt.Color(0, 0, 0));
        LBLIntroduzcaRut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLIntroduzcaRut.setText("Introduzca el RUT");

        LBLNombre.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LBLNombre.setForeground(new java.awt.Color(0, 0, 0));
        LBLNombre.setText("NOMBRE");

        LBLRut.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LBLRut.setForeground(new java.awt.Color(0, 0, 0));
        LBLRut.setText("Rut:");

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonVolverMenuPrincipal.setText("VOLVER");
        BotonVolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverMenuPrincipalActionPerformed(evt);
            }
        });

        TextSalidaDeNombre.setEditable(false);

        TextSalidaDeMesa.setEditable(false);

        LBLMesa.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LBLMesa.setForeground(new java.awt.Color(0, 0, 0));
        LBLMesa.setText("MESA:");

        TextSalidaDeRut.setEditable(false);

        LBLVocal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LBLVocal.setForeground(new java.awt.Color(0, 0, 0));
        LBLVocal.setText("VOCAL:");

        TextSalidaDeVocal.setEditable(false);
        TextSalidaDeVocal.setText("SI  /  NO");

        javax.swing.GroupLayout BackgroundBuscarPorRutLayout = new javax.swing.GroupLayout(BackgroundBuscarPorRut);
        BackgroundBuscarPorRut.setLayout(BackgroundBuscarPorRutLayout);
        BackgroundBuscarPorRutLayout.setHorizontalGroup(
            BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                .addGroup(BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                        .addComponent(LBLNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextSalidaDeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                        .addComponent(LBLRut)
                        .addGap(55, 55, 55)
                        .addComponent(TextSalidaDeRut, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                        .addComponent(LBLMesa)
                        .addGap(16, 16, 16)
                        .addComponent(TextSalidaDeMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(LBLVocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextSalidaDeVocal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonVolverMenuPrincipal)
                    .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLIntroduzcaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                                .addComponent(TextEntraRut, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(BotonBuscar)))))
                .addGap(10, 10, 10))
        );
        BackgroundBuscarPorRutLayout.setVerticalGroup(
            BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                .addComponent(PanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(LBLIntroduzcaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBuscar)
                    .addComponent(TextEntraRut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLNombre)
                    .addComponent(TextSalidaDeNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LBLRut))
                    .addComponent(TextSalidaDeRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLMesa)
                    .addGroup(BackgroundBuscarPorRutLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(BackgroundBuscarPorRutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextSalidaDeMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLVocal)
                            .addComponent(TextSalidaDeVocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(BotonVolverMenuPrincipal)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackgroundBuscarPorRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackgroundBuscarPorRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverMenuPrincipalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuPrincipal.setVisible(true);
        
    }//GEN-LAST:event_BotonVolverMenuPrincipalActionPerformed
    private boolean enviarDatos(){
        String rut = TextEntraRut.getText();
        if(valpo.buscarRut(rut, true) == null){
             JOptionPane.showMessageDialog(this, "No se encontro resultado", "NO EXISTE", JOptionPane.INFORMATION_MESSAGE);
            TextEntraRut.setText("");
            
        }
        TextSalidaDeNombre.setText(valpo.buscarRut(rut, true).getName());
        TextSalidaDeRut.setText(valpo.buscarRut(rut, true).getRut());
        TextSalidaDeMesa.setText(Integer.toString(valpo.buscarRut(rut, true).getNMesa()));
        
        if(valpo.buscarRut(rut, true).retornaTipo()){
            TextSalidaDeVocal.setText("NO");
        }else{
            TextSalidaDeVocal.setText("SI");
        }
        TextEntraRut.setText("");
        TextEntraRut.requestFocus();
        return true;
    }
    
    private void TextEntraRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEntraRutActionPerformed
        // TODO add your handling code here:
        enviarDatos();
    }//GEN-LAST:event_TextEntraRutActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        enviarDatos();
    }//GEN-LAST:event_BotonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundBuscarPorRut;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonVolverMenuPrincipal;
    private javax.swing.JLabel LBLIntroduzcaRut;
    private javax.swing.JLabel LBLMesa;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLRut;
    private javax.swing.JLabel LBLTITULO;
    private javax.swing.JLabel LBLVocal;
    private javax.swing.JPanel PanelTitulo;
    private javax.swing.JTextField TextEntraRut;
    private javax.swing.JTextField TextSalidaDeMesa;
    private javax.swing.JTextField TextSalidaDeNombre;
    private javax.swing.JTextField TextSalidaDeRut;
    private javax.swing.JTextField TextSalidaDeVocal;
    // End of variables declaration//GEN-END:variables
}
