
package ventanas;

import com.mycompany.gestionvotantes.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class CrearMesaVentana extends javax.swing.JDialog {

    /**
     * Creates new form CrearMesaVentana
     */
    //declaration de variables
    private JFrame MenuPrincipal;
    private LugarVotacion valpo = new LugarVotacion();
    
    
    public CrearMesaVentana(java.awt.Frame parent, boolean modal, LugarVotacion valparaiso) {
        super(parent, modal);
        MenuPrincipal = (JFrame) parent;
        valpo = valparaiso;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundCrearMesa = new javax.swing.JPanel();
        LBLcrearMesa = new javax.swing.JLabel();
        BOTONVOLVER = new javax.swing.JButton();
        textNumeroMesa = new javax.swing.JTextField();
        LBLNumeroMesa = new javax.swing.JLabel();
        BotonCrearMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BackgroundCrearMesa.setBackground(new java.awt.Color(0, 153, 204));

        LBLcrearMesa.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LBLcrearMesa.setForeground(new java.awt.Color(0, 0, 0));
        LBLcrearMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLcrearMesa.setText("CREAR MESA");

        BOTONVOLVER.setText("VOLVER");
        BOTONVOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONVOLVERActionPerformed(evt);
            }
        });

        textNumeroMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroMesaActionPerformed(evt);
            }
        });

        LBLNumeroMesa.setBackground(new java.awt.Color(0, 0, 0));
        LBLNumeroMesa.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LBLNumeroMesa.setForeground(new java.awt.Color(0, 0, 0));
        LBLNumeroMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLNumeroMesa.setText("Ingrese Numero de Mesa");

        BotonCrearMesa.setText("Crear Mesa");
        BotonCrearMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundCrearMesaLayout = new javax.swing.GroupLayout(BackgroundCrearMesa);
        BackgroundCrearMesa.setLayout(BackgroundCrearMesaLayout);
        BackgroundCrearMesaLayout.setHorizontalGroup(
            BackgroundCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearMesaLayout.createSequentialGroup()
                .addGroup(BackgroundCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearMesaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BOTONVOLVER, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundCrearMesaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LBLcrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundCrearMesaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(BackgroundCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLNumeroMesa)
                            .addGroup(BackgroundCrearMesaLayout.createSequentialGroup()
                                .addComponent(textNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(BotonCrearMesa)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        BackgroundCrearMesaLayout.setVerticalGroup(
            BackgroundCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLcrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LBLNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundCrearMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCrearMesa))
                .addGap(92, 92, 92)
                .addComponent(BOTONVOLVER, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackgroundCrearMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONVOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONVOLVERActionPerformed
        // TODO add your handling code here:
        //cerrar ventana de Dialoj
        this.dispose();
        //visibilidad de ventanas
        MenuPrincipal.setVisible(true);//con esto se hace visible la ventana principal
    }//GEN-LAST:event_BOTONVOLVERActionPerformed
    private boolean enviarDatos() {
            // Obtiene los valores de los campos de texto y realiza la acción para enviar los datos al programa
            int numeroMesa = Integer.parseInt(textNumeroMesa.getText());
            // Realiza la acción con los datos (p. ej., enviar los valores al programa principal)
             
            if(valpo.mesaExiste(numeroMesa)== true ){
                JOptionPane.showMessageDialog(this, "La Mesa "+ numeroMesa+" ya Existe", "Error", JOptionPane.INFORMATION_MESSAGE);
                // Limpia los campos de texto
                textNumeroMesa.setText("");
                // Establece el enfoque en el primer campo de texto
                textNumeroMesa.requestFocus();
                return false;
            }
             //ASIGNO los datos a la nueva mesa;
            Mesa mesaNueva = new Mesa(numeroMesa);
            //meto los datos al hashmap
            valpo.crearMesa(mesaNueva);
            //manda mensaje de aprobacion
            JOptionPane.showMessageDialog(this, "Datos enviados con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            // Limpia los campos de texto
            textNumeroMesa.setText("");
            // Establece el enfoque en el primer campo de texto
            textNumeroMesa.requestFocus();
            return true;
        }
    private void textNumeroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroMesaActionPerformed
       // TODO add your handling code here:
       enviarDatos();
    }//GEN-LAST:event_textNumeroMesaActionPerformed

    private void BotonCrearMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearMesaActionPerformed
        // TODO add your handling code here:
        enviarDatos();
    }//GEN-LAST:event_BotonCrearMesaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONVOLVER;
    private javax.swing.JPanel BackgroundCrearMesa;
    private javax.swing.JButton BotonCrearMesa;
    private javax.swing.JLabel LBLNumeroMesa;
    private javax.swing.JLabel LBLcrearMesa;
    private javax.swing.JTextField textNumeroMesa;
    // End of variables declaration//GEN-END:variables
}
