/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.mycompany.gestionvotantes.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class Login extends javax.swing.JFrame {

    //Declaration de mapa para guardar todo;
    LugarVotacion valpo = new LugarVotacion();
    private JFrame MenuPrincipal;
    
    public Login(LugarVotacion valparaiso, java.awt.Frame parent) {
        valpo = valparaiso;
        MenuPrincipal = (JFrame) parent;
        initComponents();
        setResizable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundLogin = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        LBLUsuario = new javax.swing.JLabel();
        LBLUsuario1 = new javax.swing.JLabel();
        textEntradaUsuario = new javax.swing.JTextField();
        jPasswordEntrada = new javax.swing.JPasswordField();
        botonEntrar = new javax.swing.JButton();
        LBLtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundLogin.setBackground(new java.awt.Color(0, 153, 204));

        panelContenido.setBackground(new java.awt.Color(0, 153, 204));

        LBLUsuario.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LBLUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LBLUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLUsuario.setText("USUARIO");

        LBLUsuario1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LBLUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        LBLUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLUsuario1.setText("CONTRASEÑA");

        textEntradaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEntradaUsuarioActionPerformed(evt);
            }
        });

        jPasswordEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordEntradaActionPerformed(evt);
            }
        });

        botonEntrar.setText("ENTRAR");
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });

        LBLtitulo.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        LBLtitulo.setForeground(new java.awt.Color(0, 0, 0));
        LBLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLtitulo.setText("LOGIN");

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                        .addComponent(LBLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                        .addComponent(LBLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                        .addComponent(LBLUsuario1)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEntrar)
                .addGap(191, 191, 191))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LBLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(LBLUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEntradaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBLUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonEntrar)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLoginLayout = new javax.swing.GroupLayout(BackgroundLogin);
        BackgroundLogin.setLayout(BackgroundLoginLayout);
        BackgroundLoginLayout.setHorizontalGroup(
            BackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        BackgroundLoginLayout.setVerticalGroup(
            BackgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean entrarALogin(){
        //asigno valores
        String rut = textEntradaUsuario.getText();
        char[] password = jPasswordEntrada.getPassword();
            String contraseña = new String(password);
        /**
        * MODO ADMIN
        * para ir al modo admin:
        */ 
        if(rut.equals("admin")){
            if(contraseña.equals("123")){
                this.setVisible(false);
                MenuPrincipal.setVisible(true);
                return true;
            }
        }
        /**
        * MODO VOCAL
        * para ir al modo vocal:
        * comprueba que el rut exista
        */
        if(valpo.buscarRut(rut, true) == null){
            JOptionPane.showMessageDialog(this, "USUARIO NO EXISTE ", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            
            textEntradaUsuario.setText("");
            jPasswordEntrada.setText("");
            textEntradaUsuario.requestFocus();
        }
        //comprueba que el usuario sean iguales
        if(valpo.buscarRut(rut, true).getRut().equals(rut)){
            
            //comprueba contraseña sean iguales
           if(contraseña.equals(valpo.buscarRut(rut, true).contraseña())){
               
              EscrutinioVentana a = new EscrutinioVentana(this, true, valpo,valpo.buscarRut(rut, true));
              this.setVisible(false);
              a.setVisible(true);
          
              return true;
           }  
        }
        
        
            JOptionPane.showMessageDialog(this, "USUARIO Y CONTRASEÑA NO CORRESPONDE ", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            textEntradaUsuario.setText("");
            jPasswordEntrada.setText("");
            textEntradaUsuario.requestFocus();
            return false;
       
    }
    
    
    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        // TODO add your handling code here:
       entrarALogin();
    }//GEN-LAST:event_botonEntrarActionPerformed

    private void jPasswordEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordEntradaActionPerformed
        // TODO add your handling code here:
        entrarALogin();
    }//GEN-LAST:event_jPasswordEntradaActionPerformed

    private void textEntradaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEntradaUsuarioActionPerformed
        // TODO add your handling code here:
        jPasswordEntrada.requestFocus();
    }//GEN-LAST:event_textEntradaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundLogin;
    private javax.swing.JLabel LBLUsuario;
    private javax.swing.JLabel LBLUsuario1;
    private javax.swing.JLabel LBLtitulo;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JPasswordField jPasswordEntrada;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JTextField textEntradaUsuario;
    // End of variables declaration//GEN-END:variables
}
