/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import com.mycompany.gestionvotantes.LugarVotacion;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class ModficarPersona extends javax.swing.JDialog {

    //declaration variables
    private JFrame MenuPrincipal;
    private LugarVotacion valpo = new LugarVotacion();
    
    
    public ModficarPersona(java.awt.Frame parent, boolean modal, LugarVotacion valparaiso) {
        super(parent, modal);
        MenuPrincipal = (JFrame) parent;
        valpo = valparaiso;
        initComponents();
        setResizable(false);
        botonEnviar.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgorud = new javax.swing.JPanel();
        LBLTitulo = new javax.swing.JLabel();
        LBLInformacion = new javax.swing.JLabel();
        LBLNombre = new javax.swing.JLabel();
        LBLRut = new javax.swing.JLabel();
        textEntradaRutBuscar = new javax.swing.JTextField();
        textEntradaNombre = new javax.swing.JTextField();
        textEntradaRut = new javax.swing.JTextField();
        textSalidaNombre = new javax.swing.JTextField();
        textSalidaRut = new javax.swing.JTextField();
        LBLNombre1 = new javax.swing.JLabel();
        LBLNuevoRut = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        botonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgorud.setBackground(new java.awt.Color(0, 153, 204));

        LBLTitulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LBLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LBLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTitulo.setText("MODIFICAR VOTANTE");

        LBLInformacion.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LBLInformacion.setForeground(new java.awt.Color(0, 0, 0));
        LBLInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLInformacion.setText("Introduzca RUT que desea Modificar");

        LBLNombre.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LBLNombre.setForeground(new java.awt.Color(0, 0, 0));
        LBLNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLNombre.setText("Nombre");

        LBLRut.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LBLRut.setForeground(new java.awt.Color(0, 0, 0));
        LBLRut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLRut.setText("RUT");

        textEntradaRutBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEntradaRutBuscarActionPerformed(evt);
            }
        });

        textEntradaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEntradaRutActionPerformed(evt);
            }
        });

        textSalidaNombre.setEditable(false);

        textSalidaRut.setEditable(false);

        LBLNombre1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LBLNombre1.setForeground(new java.awt.Color(0, 0, 0));
        LBLNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLNombre1.setText("Nuevo Nombre");

        LBLNuevoRut.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LBLNuevoRut.setForeground(new java.awt.Color(0, 0, 0));
        LBLNuevoRut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLNuevoRut.setText("Nuevo RUT");

        botonBuscar.setText("BUSCAR");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonVolver.setText("VOLVER");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonEnviar.setText("GUARDAR CAMBIOS");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgorudLayout = new javax.swing.GroupLayout(backgorud);
        backgorud.setLayout(backgorudLayout);
        backgorudLayout.setHorizontalGroup(
            backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgorudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgorudLayout.createSequentialGroup()
                        .addComponent(textSalidaRut)
                        .addGap(92, 92, 92)
                        .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLNuevoRut, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEntradaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgorudLayout.createSequentialGroup()
                        .addComponent(textSalidaNombre)
                        .addGap(90, 90, 90)
                        .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
            .addGroup(backgorudLayout.createSequentialGroup()
                .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgorudLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(textEntradaRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(botonBuscar))
                    .addGroup(backgorudLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgorudLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(LBLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgorudLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LBLRut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgorudLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(botonVolver)))
                .addGap(82, 168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgorudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEnviar)
                .addGap(39, 39, 39))
        );
        backgorudLayout.setVerticalGroup(
            backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgorudLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LBLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(LBLInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEntradaRutBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGap(18, 18, 18)
                .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLNombre)
                    .addComponent(LBLNombre1))
                .addGap(18, 18, 18)
                .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSalidaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEntradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLRut)
                    .addComponent(LBLNuevoRut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgorudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEntradaRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSalidaRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgorud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgorud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        //cerrar ventana de Dialoj
        this.dispose();
        //visibilidad de ventanas
        MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed
    private boolean buscarPersona(){
        String rut = textEntradaRutBuscar.getText();
        if(valpo.buscarRut(rut, false) == null){
             JOptionPane.showMessageDialog(this, "No se encontro resultado", "NO EXISTE", JOptionPane.INFORMATION_MESSAGE);
            textEntradaRut.setText("");
            return false;
            
        }
        textSalidaNombre.setText(valpo.buscarRut(rut, true).getName());
        textSalidaRut.setText(valpo.buscarRut(rut, true).getRut());
        textEntradaNombre.setText(valpo.buscarRut(rut, true).getName());
        textEntradaRut.setText(valpo.buscarRut(rut, true).getRut());
       
        textEntradaRutBuscar.setText("");
        textEntradaNombre.requestFocus();
        return true;
        
    }
    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        if(buscarPersona()){
            botonEnviar.setEnabled(true); 
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void textEntradaRutBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEntradaRutBuscarActionPerformed
        // TODO add your handling code here:
        if(buscarPersona()){
            botonEnviar.setEnabled(true); 
        }
    }//GEN-LAST:event_textEntradaRutBuscarActionPerformed
    private boolean enviarDatos(){
        String rut = textSalidaRut.getText();
        String nombreNuevo = textEntradaNombre.getText();
        String rutNuevo = textEntradaRut.getText();
        if(nombreNuevo.equals("")){
            JOptionPane.showMessageDialog(this, "Nombre no puede estar vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if(rutNuevo.equals("")){
                JOptionPane.showMessageDialog(this, "RUT no puede estar vacio", "ERROR", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        valpo.buscarRut(rut, false).setName(nombreNuevo);
        valpo.buscarRut(rut, false).setRut(rutNuevo);
        JOptionPane.showMessageDialog(this, "SE MODIFICO CON EXITO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            
        //limpio
        textEntradaNombre.setText("");
        textEntradaRut.setText("");
        textSalidaNombre.setText("");
        textSalidaRut.setText("");
        botonEnviar.setEnabled(false); 
        return true;
    }
    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        // TODO add your handling code here:
        enviarDatos();
           
        
    }//GEN-LAST:event_botonEnviarActionPerformed

    private void textEntradaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEntradaRutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textEntradaRutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLInformacion;
    private javax.swing.JLabel LBLNombre;
    private javax.swing.JLabel LBLNombre1;
    private javax.swing.JLabel LBLNuevoRut;
    private javax.swing.JLabel LBLRut;
    private javax.swing.JLabel LBLTitulo;
    private javax.swing.JPanel backgorud;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField textEntradaNombre;
    private javax.swing.JTextField textEntradaRut;
    private javax.swing.JTextField textEntradaRutBuscar;
    private javax.swing.JTextField textSalidaNombre;
    private javax.swing.JTextField textSalidaRut;
    // End of variables declaration//GEN-END:variables
}
