/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JFrame;

/**
 *
 * @author esteb
 */
public class MostrarTodoVentana extends javax.swing.JDialog {

    /**
     * Creates new form MostrarTodoVentana
     */
    //declaration de variables
    
    private JFrame MenuPrincipal;
    
    
    
    public MostrarTodoVentana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        MenuPrincipal = (JFrame) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundMostrarTodo = new javax.swing.JPanel();
        LBLMostrarTodo = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BackgroundMostrarTodo.setBackground(new java.awt.Color(0, 153, 204));

        LBLMostrarTodo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        LBLMostrarTodo.setForeground(new java.awt.Color(0, 0, 0));
        LBLMostrarTodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLMostrarTodo.setText("MOSTRAR TODO");

        BotonVolver.setText("VOLVER");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundMostrarTodoLayout = new javax.swing.GroupLayout(BackgroundMostrarTodo);
        BackgroundMostrarTodo.setLayout(BackgroundMostrarTodoLayout);
        BackgroundMostrarTodoLayout.setHorizontalGroup(
            BackgroundMostrarTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundMostrarTodoLayout.createSequentialGroup()
                .addGroup(BackgroundMostrarTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundMostrarTodoLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(LBLMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundMostrarTodoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        BackgroundMostrarTodoLayout.setVerticalGroup(
            BackgroundMostrarTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundMostrarTodoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LBLMostrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                .addComponent(BotonVolver)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundMostrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundMostrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        //cerrar ventana de Dialoj
        this.dispose();
        //visibilidad de ventanas
        MenuPrincipal.setVisible(true);//con esto se hace visible la ventana principal
    }//GEN-LAST:event_BotonVolverActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundMostrarTodo;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel LBLMostrarTodo;
    // End of variables declaration//GEN-END:variables
}
